### ISSUE TITLE
Insertion Point location

### ISSUE THREAD

**Issue by ben-ole** [kyle-n/HighlightedTextView#24]
**Is your feature request related to a problem? Please describe.**
I'd like to build an auto-completion feature on top, hence I need to know the position of the insertion point.

Is there any possibility to get the location at the moment?

**Comment by santi-g-s** [comment]
As far as I know, the simplest way to achieve this would be to leverage `textView.selectedRange`  whenever the selected range changes, however I'm not sure if this is the case given your CustomTextView wrapper. I imagine it is still possible though.

**Comment by santi-g-s** [comment]
Hi @kyle-n. I worked on this for a bit this morning and got something that works out. What do you think?

Inside `HighlightedTextEditor` I added:
```
var onSelectionChange: (NSRange) -> Void = { _ in }
```
And updated the init to include it:
```
public init(
   text: Binding<String>,
   highlightRules: [HighlightRule],
   onEditingChanged: @escaping () -> Void = {},      
   onCommit: @escaping () -> Void = {},
   onTextChange: @escaping (String) -> Void = { _ in },
   onSelectionChange: @escaping (NSRange) -> Void = { NSRange in } // <- Here
) {
   _text = text
   self.highlightRules = highlightRules
   self.onEditingChanged = onEditingChanged
   self.onCommit = onCommit
   self.onTextChange = onTextChange
   self.onSelectionChange = onSelectionChange
}
```

Then in the coordinator I added the following:

```
public func textViewDidChangeSelection(_ notification: Notification) {
   guard let textView = notification.object as? NSTextView else {
       return
   }
   DispatchQueue.main.async {
       self.parent.onSelectionChange(textView.selectedRange())
   }
}

````

For @ben-ole, the insertion pointer would be the location of the NSRange.

Would you (@kyle-n )consider implementing this?

**Comment by kyle-n** [comment]
@santi-g-s Definitely! Thank you for the code, that was a great way to get started. 

@ben-ole @santi-g-s I've put up a first draft PR #33, please let me know what you think. 

- I wanted to make `onSelectionChange` a modifier, instead of an `init()` argument, since that `init()` function is already overloaded with too many arguments. 
- `NSTextView` actually accepts multiple selected ranges, so I have set up the callback to accept `[NSRange]`. However, since this isn't on `UITextView` and writing `ranges.first` all the time would be annoying for UIKit developers, I've also added a convenience initializer that accepts a callback only using the first `selectedRange`.

**Comment by santi-g-s** [comment]
@kyle-n Brilliant! 

I also wanted to do it through a modifier but didn't know how - much more elegant. Thank you for the quick work!

**Comment by kyle-n** [comment]
Alright, [it's shipped](https://github.com/kyle-n/HighlightedTextEditor/releases/tag/1.7.0)!
