### ISSUE TITLE
TextEditor disappears when embedded inside ScrollView or List

### ISSUE THREAD

**Issue by NSCoder** [kyle-n/HighlightedTextView#58]
**Describe the bug**
When adding an instance of `HighlightedTextEditor` inside a `ScrollView` or a `List`, it disappears from the screen

**To Reproduce**
1. Create a SwiftUI list and add some views and a single `HighlightedTextEditor`
2. Run the application

**Expected behavior**
The `HighlightedTextEditor` should be presented and it should share the scrollview of its parent view (either List or Scrollview)

**Environment**
AppKit, macOS Monterey

**Additional context**
This seems to be related to having two scrolls nested (one of the list and one of NSTextView). I'm not sure at this point that there is a viable fix but I wanted to mention it because `TextEditor` works correctly under this circumstances. 

One idea that I have is that when HighlightedTextEditor is displayed inside a ScrollView, it should grow its size to match the contentSize. Effectively disabling the scrollview of NSTextView and providing a content size for the parent view. (I tried to make this happen but I didn't have a lot of luck)

**Comment by kyle-n** [comment]
Verified the bug is happening on iOS 15.2 Simulator and macOS Big Sur.

Sample code:

```swift
struct ContentView: View {
    
    @State private var text: String = """
    Anything goes here
    """
    
    var body: some View {
        VStack {
            Group {
                ScrollView {
                    HighlightedTextEditor(text: $text, highlightRules: .markdown)
                        .border(Color.red)
                }
            }
                .frame(height: 100)
            Group {
                TextEditor(text: $text)
            }
            .frame(height: 100)
        }
    }
}
```

Run the above snippet in an AppKit or UIKit project and in both cases, HLTE will not appear. Change the `ScrollView` to a `Vstack` and it appears with the red border. 

@NSCoder Thank you for reporting this. I'm not sure how to fix it. Seems like it'll require diving deep into how UIKit and AppKit draw SwiftUI content. I'll give it a look.

**Comment by kyle-n** [comment]
@NSCoder Sorry for the late reply, things have been busy. 

I've looked into this and it's not a bug. Basically some SwiftUI views [have an `intrinsicContentSize`](https://zalogatomek.medium.com/swiftui-missing-intrinsic-content-size-how-to-get-it-6eca8178a71f), and some don't. HLTE intentionally does not have an intrinsic height. It will grow to fit whatever container it's placed inside. If it's inside a `ScrollView`, the `ScrollView` forces HLTE to run at its intrinsic height, which is zero. So the way to fix this is:

```swift
HighlightedTextEditor(text: $text, highlightRules: .markdown)
    .frame(height: 200)
```

Where `200` can be anything you need it to be. I think you'll have to use `GeometryReader` to make HLTE share the height of its parent `ScrollView`. 

HLTE does not and should not have an intrinsic height, since it is a scrolling text editor view.

**Comment by henningko** [comment]
@NSCoder what's the workaround you ended up using?

**Comment by henningko** [comment]
When using a simple TextView, adding `sizeThatFits(...)` (taken from [this discussion](https://github.com/danielsaidi/RichTextKit/issues/33#issuecomment-1514597879) for RichTextKit) does the trick, without breaking the "normal" scrolling functionality should you prefer that:
```swift
struct TextView: UIViewRepresentable {
    @Binding var text: String
    
    func makeUIView(context: Context) -> UITextView {
        let view = UITextView()
        view.isScrollEnabled = false
        view.isEditable = true
        view.isUserInteractionEnabled = true
        view.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
        view.delegate = context.coordinator
        view.font = UIFont.preferredFont(forTextStyle: .body)
        return view
    }
    
    func updateUIView(_ uiView: UITextView, context: Context) {
        uiView.text = text
    }
    
    func makeCoordinator() -> TextView.Coordinator {
        Coordinator(self)
    }
    
    class Coordinator: NSObject, UITextViewDelegate {
        var control: TextView
        
        init(_ control: TextView) {
            self.control = control
        }
        
        func textViewDidChange(_ textView: UITextView) {
            control.text = textView.text
            //            control.text.updateChangeCount(.done)
        }
    }
    
    func sizeThatFits(_ proposal: ProposedViewSize, uiView: UITextView, context: Context) -> CGSize? {
        // make sure we have a valid proposed width:
        guard let proposedWidth = proposal.width, proposedWidth > 0, proposedWidth < .infinity else {
            return nil
        }
        
        // calculate size of UITextView that fits current text:
        var sizeThatFits = uiView.sizeThatFits(CGSize(
            width: proposedWidth,
            height: .greatestFiniteMagnitude
        ))
        
        // fill parent horizontally:
        sizeThatFits.width = proposedWidth
        
        return sizeThatFits
    }
}
```

I tried using this as an extension to HighlightedTextEditor:
```swift
public extension HighlightedTextEditor {
    func sizeThatFits(_ proposal: ProposedViewSize, uiView: UITextView, context: Context) -> CGSize? {
    ... see above
    }
}
```

But that, unfortunately, wasn't enough to get it to work.
